<a href="https://colab.research.google.com/github/Tanupanchal26/VLAUE_ADDED-COURSE/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
print(np.__version__)
a = np.array([5,2,8,1,3])
print((a))

2.0.2
[5 2 8 1 3]


In [15]:
import numpy as np

a1 = np.array([5,2,8,1,3])
print(a1)
print(a1.ndim)
print(a1.size)
print(a1.shape)
print(a1.dtype)
print(type(a1))



[5 2 8 1 3]
1
5
(5,)
int64
<class 'numpy.ndarray'>


In [16]:
import numpy as np
a3 = np.array([[[5,2,8,1,3],[1,2,3,4,5],[14,52,4,6,8]],
               [[10,15,8,1,3],[9,6,5,4,5],[14,52,4,6,8]]])
print(a3)
print(a3.ndim)
print(a3.size)
print(a3.shape)
print(a3.dtype)
print(type(a3))

[[[ 5  2  8  1  3]
  [ 1  2  3  4  5]
  [14 52  4  6  8]]

 [[10 15  8  1  3]
  [ 9  6  5  4  5]
  [14 52  4  6  8]]]
3
30
(2, 3, 5)
int64
<class 'numpy.ndarray'>


In [14]:
import numpy as np
a2 = np.array([[5,2,8,1,3],
               [1,2,3,4,5]])
print(a2)
print(a2.ndim)
print(a2.size)

print(a2.dtype)
print(a2.shape)
print(type(a2))

[[5 2 8 1 3]
 [1 2 3 4 5]]
2
10
int64
<class 'numpy.ndarray'>


**CREATING ARRAY **

 np.array()

np.ones()

np.zeros()

np.random.rand(5,3)

np.random.randint(10,size=5)

In [24]:
ones=np.ones((12,1))
ones.astype(int)


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [27]:
zeros=np.zeros((2,3,1))
zeros.astype(int)

array([[[0],
        [0],
        [0]],

       [[0],
        [0],
        [0]]])