<a href="https://colab.research.google.com/github/Tanupanchal26/VLAUE_ADDED-COURSE/blob/main/TASK_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("----- 1D ARRAY -----")
a1 = np.array([10,20,30,40,50,60,70,80])

print("1:", a1[2:7])
print("2:", a1[:5])
print("3:", a1[1:-1])
print("4:", a1[::2])
print("5:", a1[-3:])
print("6:", a1[-6:-2])
print("7:", a1[::-1])
print("8:", a1[1:-1])
print("9:", a1[::-2])
print("10:", a1[2:5])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
15
[10 11 12]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[[ 4  5  6]]

 [[13 14 15]]

 [[22 23 24]]]
[1 5 9]
[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]


In [ ]:
import numpy as np

print("\n----- 2D ARRAY -----")
a2 = np.array([
[1,2,3,4],
[5,6,7,8],
[9,10,11,12],
[13,14,15,16]
])

print("1:", a2[1])
print("2:", a2[:,2])
print("3:", a2[1:3,1:3])
print("4:", a2[:2,:])
print("5:", a2[:,-2:])
print("6:", a2[-1])
print("7:", a2[:,-1])
print("8:", a2[::-1])
print("9:", a2[1:3,1:3])
print("10:", a2[1:-1,1:-1])

In [2]:
import numpy as np
print("\n----- 3D ARRAY -----")
a3 = np.array([
[[1,2,3],[4,5,6],[7,8,9]],
[[10,11,12],[13,14,15],[16,17,18]],
[[19,20,21],[22,23,24],[25,26,27]]
])

print("1:\n", a3[0])
print("2:\n", a3[-2])
print("3:", a3[1,1,2])
print("4:", a3[1,0])
print("5:\n", a3[:,:, -1])
print("6:\n", a3[:2])
print("7:\n", a3[1])
print("8:\n", a3[:,1:-1,0:2])
print("9:", np.diag(a3[0]))
print("10:\n", a3[::-1])


----- 3D ARRAY -----
1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
3: 15
4: [10 11 12]
5:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
6:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
7:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
8:
 [[[ 4  5]]

 [[13 14]]

 [[22 23]]]
9: [1 5 9]
10:
 [[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
